# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\user\Desktop\튜터링_프로젝트 파이\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1089, 803)
        self.timelimit = QtWidgets.QLineEdit(Dialog)
        self.timelimit.setGeometry(QtCore.QRect(90, 50, 211, 31))
        self.timelimit.setObjectName("timelimit")
        self.timelimit_2 = QtWidgets.QLineEdit(Dialog)
        self.timelimit_2.setGeometry(QtCore.QRect(90, 90, 211, 31))
        self.timelimit_2.setObjectName("timelimit_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 60, 81, 51))
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.plainTextEdit.setPlainText(_translate("Dialog", "제한 시간:\n"
"할일 목록:"))
